### ISSUE TITLE
MongoNetworkError: failed to connect to server ( running on mac os)

### ISSUE THREAD

**Issue by hamashexler** [bmatusiak/welder-pos#1]
MongoNetworkError: failed to connect to server [localhost:8080] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:8080]
    at Pool.<anonymous> (/Users/HamaShexler/Downloads/pos3/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/Users/HamaShexler/Downloads/pos3/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/Users/HamaShexler/Downloads/pos3/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by bmatusiak** [comment]
i know its been a few years, but this requires mongodb to use for database storage
